refactor!: change model to expect mel-band oriented tensors instead of time-oriented ones
EveryVoiceTTS/HiFiGAN_iSTFT_lightning pull request #39
Opened 2024-10-30 01:18 UTC by roedoejet

2024-11-06 16:57 UTC, SamuelLarkin requested changes
make the code a little bit more readable

2024-12-09 22:48 UTC, joanise requested changes
Please accept Sam's change request, otherwise this looks fine.

2024-12-09 22:48 UTC, joanise commented on hfgl/cli.py
> +        )
Yes, please accept this suggestion, the code is quite hard to read.

2024-12-09 22:48 UTC, joanise commented on hfgl/cli.py
> +            f"We expected the first dimension of your Mel spectrogram to correspond with the number of Mel bands declared by your model ({checkpoint['hyper_parameters']['config']['preprocessing']['au
This warning message is good, probably giving the user the feedback I was asking for in the top-level PR.

2024-12-09 22:49 UTC, joanise commented
Note: you'll need to rebase, and solve the merge conflict: we now have to use `shell_complete`, not `autocompletion`.

2024-12-17 18:17 UTC, merged